
import { Button, HorizontalBox, GroupBox, TextEdit, LineEdit } from "std-widgets.slint";


export component AppWindow inherits Window {
    title: "TextEdit";
    in-out property <string> content;
    in-out property <bool> wrap;
    in-out property <int> page_num;
    callback show_text();
    callback prev_page();
    callback next_page();
    // description: "Similar to LineEdit, but can be used to enter several lines of text. The widget can be imported";
    min-width: 600px;
    min-height: 400px;
    

    VerticalLayout {
        // visible: false;
        HorizontalBox {
            LineEdit {
                text: "Enter text here";
            }
            Button {
                text: "show text";
                clicked => {
                    root.show_text();
                }
            }
            Button {
                text: "prev page";
                clicked => {
                    root.page_num -= 1;
                    root.prev_page();
                }
            }
            Button {
                text: "next page";
                clicked => {
                    root.page_num += 1;
                    root.next_page();
                }
            }
        }
        
        GroupBox {
            // visible: true;
            // title: "Word-Wrap";
            te1 := TextEdit {
                text: content;
                horizontal-alignment: left;
                wrap: word-wrap;
            }
        }
    }
}